name = "verycool-proxy-worker"
# account_id: fill this from your Cloudflare dashboard (Workers -> Overview)
# zone_id: optional, only necessary if you want to bind a route on a domain
# type = "javascript"  # default for Wrangler 2+
# For local dev and publishing via wrangler you need to set account_id below.

# Example:
# account_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# zone_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# Optional: enable workers_dev for a workers.dev subdomain
workers_dev = true

# Build and publish settings (default is fine for this single-file worker)
# If using modules or bundlers, adjust here.

[vars]
# Configure these values for your deployment
# TARGET_URL: set to the API target you want the worker to forward to (recommended)
# e.g. TARGET_URL = "https://api.verymobile.it/frontend/crc/WindTre?output=json"
# ALLOWED_ORIGINS: comma-separated list of allowed origins, or "*" for permissive
# e.g. ALLOWED_ORIGINS = "https://g4s01.github.io"
TARGET_URL = "https://api.verymobile.it/frontend/crc/WindTre?output=json"
ALLOWED_ORIGINS = "https://g4s01.github.io"
WORKER_ALLOW_ANY_TARGET = "false"
# If you want the worker to inject an upstream auth header from a secret:
# UPSTREAM_AUTH_HEADER = "Authorization"

# Note: To provide a secret UPSTREAM_AUTH_TOKEN, run:
#   wrangler secret put UPSTREAM_AUTH_TOKEN